version: "3.9"
services:
    nginx:
        image: nginx:1.23-alpine
        ports:
            - 80:80
        restart: always
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    backend:
        build: ./backend
        restart: always
        volumes:
            - ./backend/.env.docker:/app/backend/.env:ro
            - db-data:/app/persistence
    frontend:
        build: ./frontend
        restart: always
        volumes:
            - ./frontend/.env.docker.local:/app/.env.local:ro

volumes:
    db-data:
